[2025-04-01T04:26:01.124+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T04:26:01.140+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v02.task1 manual__2025-04-01T04:26:00.487010+00:00 [queued]>
[2025-04-01T04:26:01.149+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v02.task1 manual__2025-04-01T04:26:00.487010+00:00 [queued]>
[2025-04-01T04:26:01.149+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-04-01T04:26:01.163+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-04-01 04:26:00.487010+00:00
[2025-04-01T04:26:01.171+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=26416) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-01T04:26:01.170+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v02', 'task1', 'manual__2025-04-01T04:26:00.487010+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpd6voyg8o']
[2025-04-01T04:26:01.172+0000] {standard_task_runner.py:72} INFO - Started process 26417 to run task
[2025-04-01T04:26:01.172+0000] {standard_task_runner.py:105} INFO - Job 128: Subtask task1
[2025-04-01T04:26:01.218+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_backfill_v02.task1 manual__2025-04-01T04:26:00.487010+00:00 [running]> on host 9663692256f6
[2025-04-01T04:26:01.306+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rajesh' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backfill_v02' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T04:26:00.487010+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T04:26:00.487010+00:00'
[2025-04-01T04:26:01.307+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T04:26:01.323+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-01T04:26:01.324+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2025-04-01T04:26:01.332+0000] {subprocess.py:99} INFO - Output:
[2025-04-01T04:26:01.334+0000] {subprocess.py:106} INFO - This is a simple bash command!
[2025-04-01T04:26:01.334+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-01T04:26:01.358+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T04:26:01.359+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backfill_v02, task_id=task1, run_id=manual__2025-04-01T04:26:00.487010+00:00, execution_date=20250401T042600, start_date=20250401T042601, end_date=20250401T042601
[2025-04-01T04:26:01.399+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T04:26:01.415+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-01T04:26:01.416+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
