[2025-04-01T04:13:13.503+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T04:13:13.518+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v02.task1 scheduled__2025-03-31T00:00:00+00:00 [queued]>
[2025-04-01T04:13:13.527+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v02.task1 scheduled__2025-03-31T00:00:00+00:00 [queued]>
[2025-04-01T04:13:13.528+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-04-01T04:13:13.540+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-03-31 00:00:00+00:00
[2025-04-01T04:13:13.546+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=25752) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-01T04:13:13.547+0000] {standard_task_runner.py:72} INFO - Started process 25753 to run task
[2025-04-01T04:13:13.546+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v02', 'task1', 'scheduled__2025-03-31T00:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp_yyw009w']
[2025-04-01T04:13:13.548+0000] {standard_task_runner.py:105} INFO - Job 126: Subtask task1
[2025-04-01T04:13:13.588+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_backfill_v02.task1 scheduled__2025-03-31T00:00:00+00:00 [running]> on host 9663692256f6
[2025-04-01T04:13:13.674+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rajesh' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backfill_v02' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-31T00:00:00+00:00'
[2025-04-01T04:13:13.676+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T04:13:13.697+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-01T04:13:13.698+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2025-04-01T04:13:13.705+0000] {subprocess.py:99} INFO - Output:
[2025-04-01T04:13:13.708+0000] {subprocess.py:106} INFO - This is a simple bash command!
[2025-04-01T04:13:13.708+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-01T04:13:13.738+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T04:13:13.738+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backfill_v02, task_id=task1, run_id=scheduled__2025-03-31T00:00:00+00:00, execution_date=20250331T000000, start_date=20250401T041313, end_date=20250401T041313
[2025-04-01T04:13:13.772+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T04:13:13.786+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-01T04:13:13.787+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
